In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [21]:
df = pd.read_csv("Weather and Temperature Logs(February 2026).csv")
df.head()

,Time Stamp,Current Weather,Temp (C),Humidity,Barometric Pressue (Pa),Wind Direction,Wind Speed (m/s),Wind Chill (C),Heat Index (C)
0,2/1/2026 0:15:00,Cloudy,-11.4,60.644017,101420.0,320.0,14.76,-18.385102,NaN
1,2/1/2026 0:35:00,Mostly Cloudy,-11.5,61.647019,101390.0,310.0,9.36,-16.787109,NaN
2,2/1/2026 0:55:00,Clear,-11.6,61.620911,101320.0,310.0,22.32,-20.310614,NaN
3,2/1/2026 1:15:00,Clear,-12.1,64.140316,101360.0,320.0,16.56,-19.708570,NaN
4,2/1/2026 1:35:00,Clear,-12.3,64.090342,101390.0,310.0,12.96,-18.978616,NaN

In [23]:
df = df.drop("Wind Direction", axis=1)
df = df.drop("Heat Index (C)", axis=1)

In [25]:
df.head()

,Time Stamp,Current Weather,Temp (C),Humidity,Barometric Pressue (Pa),Wind Speed (m/s),Wind Chill (C)
0,2/1/2026 0:15:00,Cloudy,-11.4,60.644017,101420.0,14.76,-18.385102
1,2/1/2026 0:35:00,Mostly Cloudy,-11.5,61.647019,101390.0,9.36,-16.787109
2,2/1/2026 0:55:00,Clear,-11.6,61.620911,101320.0,22.32,-20.310614
3,2/1/2026 1:15:00,Clear,-12.1,64.140316,101360.0,16.56,-19.708570
4,2/1/2026 1:35:00,Clear,-12.3,64.090342,101390.0,12.96,-18.978616

In [ ]:
R_wall = 3.0
A_envelope = 70
ACH = 0.5
volume = 30

In [ ]:
df["R_wall"] = R_wall
df["A_envelope"] = A_envelope
df["ACH"] = ACH
df["volume"] = volume